spring.application.name=equi-track

# MySQL Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/equitrack?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password= MySQL Password

# Hibernate Settings (Auto-creates tables)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# External Stock API
stock.api.key= API Key 
stock.api.url=https://finnhub.io/api/v1/quote
